# Propriedades do bando de dados
spring:
  datasource:
    url: jdbc:mysql://localhost/testedb?useSSL=false&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl_auto: create

# Propriedades de Hibernate
# O dialeto SQL faz com que o Hibernate gere um SQL melhor para o banco de dados escolhido
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

# propriedades para mostrar o sql no console e formatar em uma forma mais legivel
#spring.jpa.properties.hibernate.format_sql=true
    show-sql: true
