# Propriedades do bando de dados
spring:
  datasource:
    url: mysql://b5573bbfc10449:30128700@us-cdbr-east-05.cleardb.net/heroku_d405a5441cbb008?reconnect=true

  jpa:
    hibernate:
      ddl_auto: none

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false

    show-sql: false